# Generated by Django 5.1.3 on 2025-01-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attender_username', models.CharField(max_length=50, unique=True)),
                ('attender_email', models.EmailField(max_length=255, unique=True)),
                ('attender_password', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
