# Generated by Django 5.1.3 on 2024-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=110)),
            ],
        ),
    ]
