# Generated by Django 5.1.3 on 2025-01-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Organizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=50, unique=True)),
                ('organizer_email', models.EmailField(max_length=255, unique=True)),
                ('organizer_password', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Active_Organizer',
            fields=[
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organizer.all_organizer')),
            ],
        ),
    ]
