# Generated by Django 5.1.3 on 2025-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0003_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_billboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
