# Generated by Django 5.1.3 on 2025-02-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0004_alter_customuser_profile_picture'),
        ('eventmodule', '0004_event_is_billboard_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': 'Organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='eventhub_user.customuser'),
        ),
    ]
