# Generated by Django 5.1.3 on 2025-02-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0004_alter_customuser_profile_picture'),
        ('eventmodule', '0005_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='eventhub_user.customuser'),
        ),
    ]
