# Generated by Django 5.1.3 on 2025-02-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0004_alter_customuser_profile_picture'),
        ('eventmodule', '0006_alter_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_comments', to='eventhub_user.customuser')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eventmodule.event')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='eventhub_user.customuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='eventhub_user.customuser')),
            ],
        ),
    ]
