# Generated by Django 5.1.3 on 2025-02-17 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0010_remove_event_ticket_price_tickettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
