# Generated by Django 5.1.3 on 2025-02-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0011_alter_tickettype_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.IntegerField(),
        ),
    ]
