# Generated by Django 5.1.3 on 2025-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0012_alter_tickettype_end_date_alter_tickettype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickettypeno',
            field=models.IntegerField(default=1),
        ),
    ]
