# Generated by Django 5.1.3 on 2025-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0013_event_tickettypeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickettypeno',
            field=models.IntegerField(default=0),
        ),
    ]
