# Generated by Django 5.1.3 on 2025-03-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0015_event_attendees_alter_event_tickettypeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
