# Generated by Django 5.1.7 on 2025-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0017_event_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
