# Generated by Django 5.1.7 on 2025-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0020_remove_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
    ]
