# Generated by Django 5.1.7 on 2025-04-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0021_remove_ticket_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='purchased_by',
            field=models.ManyToManyField(related_name='purchased_ticket_types', through='eventmodule.TicketPurchase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmodule.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
