# Generated by Django 5.1.7 on 2025-04-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0022_tickettype_purchased_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='available_quantity',
        ),
    ]
