# Generated by Django 5.1.7 on 2025-04-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0023_remove_tickettype_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='purchased_by',
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventmodule.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
