# Generated by Django 5.1.7 on 2025-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0028_ticketpurchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
