# Generated by Django 5.1.7 on 2025-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0029_ticket_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
    ]
