# Generated by Django 5.1.7 on 2025-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0032_eventrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
