# Generated by Django 5.1.7 on 2025-04-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
