# Generated by Django 5.1.7 on 2025-04-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0035_ticket_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
