# Generated by Django 5.1.7 on 2025-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0036_ticket_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
