# Generated by Django 5.1.7 on 2025-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0038_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='rsvp_url',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
