# Generated by Django 5.1.7 on 2025-04-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0039_rsvp_rsvp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('cancelled', 'Cancelled'), ('checked', 'Checked')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('checked', 'Checked'), ('verified', 'Verified')], default='in_progress', max_length=20),
        ),
    ]
