# Generated by Django 5.1.7 on 2025-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodule', '0040_alter_rsvp_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('cancelled', 'Cancelled'), ('verified', 'Verified'), ('checked', 'Checked')], default='in_progress', max_length=20),
        ),
    ]
