# Generated by Django 5.1.3 on 2025-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
