# Generated by Django 5.1.3 on 2025-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0002_alter_customuser_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
