# Generated by Django 5.1.3 on 2025-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/'),
        ),
    ]
