# Generated by Django 5.1.3 on 2025-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub_user', '0005_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee'), ('admin', 'Admin')], default='attendee', max_length=10),
        ),
    ]
